Update README to point to `psd.js` instead of `psd`
meltingice/psd.js pull request #220
Opened 2021-08-09 14:37 UTC by el-mapache

Hello! Thanks for writing such an excellent library! We've been updating one of our services that depends on this code, and ran into some installation snags in the process. Based on issue #195, it _seems_ that the npm package referenced in the README is out-of-date.

### Explanation
Pointing at `psd` downloads a version without a `dist` folder. When used in a project with `webpack`,
the package is quite difficult to build, throwing out a lot of issues with various `coffeescript` libraries. The built version of `psd` within the `psd.js` npm package
works perfectly out of the box

### Changes
This PR updates the references from `psd` to `psd.js`

2021-09-25 03:57 UTC, MgenGlder commented
@el-mapache Cheers for the suggestion and PR- it seems `psd.js` is actually a maintained fork of `psd` and `psd` is the npm package this repo is attached to. This is a pretty confusing situation since the package itself is called `psd.js` but the npm published namespace is `psd`. In any case, this shouldn't be needed but I'd be interested in reaching out to the maintainers of the other package to see if there's a way that we can collaborate.

2021-09-25 03:58 UTC, MgenGlder requested changes

2021-09-25 03:58 UTC, MgenGlder commented on README.md
> +PSD.js has no native dependencies. Simply add `psd.js` to your package.json or run `npm install psd.js`.
This is not true actually! It's extremely confusing, but the original statement is correct.

2021-09-27 12:10 UTC, el-mapache commented
Given that we are using a fork of this library, and not the library directly, this PR doesn't seem especially relevant. Thanks!

2021-09-27 12:10 UTC, closed without merging

2022-03-04 17:39 UTC, gustavopch commented
Just spent 1 hour trying to understand how to use https://npm.im/psd before finding this issue and realizing I should use https://npm.im/psd.js instead.